/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./splash.html",
    "./silverCredit.html",
    "./goldCredit.html",
    "./settings.html",
    "./dashboard.html",
    "./accountsPayable.html",
    "./accountsReceivable.html",
    "./add.html",
    "./balanceSheet.html",
    "./goldPandL.html",
    "./ledger.html",
    "./P&L.html",
    "./payments.html",
    "./purchases.html",
    "./receipts.html",
    "./sales.html",
    "./showCreditors.html",
    "./showDebtors.html",
    "./showLedgers.html",
    "./showPayments.html",
    "./showPurchase.html",
    "./showReceipts.html",
    "./showSales.html",
    "./showStock.html",
    "./silverP&L.html",
    "./stock.html",
    "./stockReport.html",
    "./books.html",

    "./styles.css",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
